/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndicesRouteImport } from './routes/indices'
import { Route as ColunasRouteImport } from './routes/colunas'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndicesSlugRouteImport } from './routes/indices.$slug'
import { Route as ColunasSlugRouteImport } from './routes/colunas.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminIndicesIndexRouteImport } from './routes/_authenticated/admin.indices.index'
import { Route as AuthenticatedAdminColunasIndexRouteImport } from './routes/_authenticated/admin.colunas.index'
import { Route as AuthenticatedAdminIndicesNewRouteImport } from './routes/_authenticated/admin.indices.new'
import { Route as AuthenticatedAdminIndicesIdRouteImport } from './routes/_authenticated/admin.indices.$id'
import { Route as AuthenticatedAdminColunasNewRouteImport } from './routes/_authenticated/admin.colunas.new'
import { Route as AuthenticatedAdminColunasIdRouteImport } from './routes/_authenticated/admin.colunas.$id'

const IndicesRoute = IndicesRouteImport.update({
  id: '/indices',
  path: '/indices',
  getParentRoute: () => rootRouteImport,
} as any)
const ColunasRoute = ColunasRouteImport.update({
  id: '/colunas',
  path: '/colunas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesSlugRoute = IndicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndicesRoute,
} as any)
const ColunasSlugRoute = ColunasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ColunasRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIndicesIndexRoute =
  AuthenticatedAdminIndicesIndexRouteImport.update({
    id: '/indices/',
    path: '/indices/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminColunasIndexRoute =
  AuthenticatedAdminColunasIndexRouteImport.update({
    id: '/colunas/',
    path: '/colunas/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIndicesNewRoute =
  AuthenticatedAdminIndicesNewRouteImport.update({
    id: '/indices/new',
    path: '/indices/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIndicesIdRoute =
  AuthenticatedAdminIndicesIdRouteImport.update({
    id: '/indices/$id',
    path: '/indices/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminColunasNewRoute =
  AuthenticatedAdminColunasNewRouteImport.update({
    id: '/colunas/new',
    path: '/colunas/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminColunasIdRoute =
  AuthenticatedAdminColunasIdRouteImport.update({
    id: '/colunas/$id',
    path: '/colunas/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colunas': typeof ColunasRouteWithChildren
  '/indices': typeof IndicesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/colunas/$slug': typeof ColunasSlugRoute
  '/indices/$slug': typeof IndicesSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/colunas/$id': typeof AuthenticatedAdminColunasIdRoute
  '/admin/colunas/new': typeof AuthenticatedAdminColunasNewRoute
  '/admin/indices/$id': typeof AuthenticatedAdminIndicesIdRoute
  '/admin/indices/new': typeof AuthenticatedAdminIndicesNewRoute
  '/admin/colunas/': typeof AuthenticatedAdminColunasIndexRoute
  '/admin/indices/': typeof AuthenticatedAdminIndicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colunas': typeof ColunasRouteWithChildren
  '/indices': typeof IndicesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/colunas/$slug': typeof ColunasSlugRoute
  '/indices/$slug': typeof IndicesSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/colunas/$id': typeof AuthenticatedAdminColunasIdRoute
  '/admin/colunas/new': typeof AuthenticatedAdminColunasNewRoute
  '/admin/indices/$id': typeof AuthenticatedAdminIndicesIdRoute
  '/admin/indices/new': typeof AuthenticatedAdminIndicesNewRoute
  '/admin/colunas': typeof AuthenticatedAdminColunasIndexRoute
  '/admin/indices': typeof AuthenticatedAdminIndicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/colunas': typeof ColunasRouteWithChildren
  '/indices': typeof IndicesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/colunas/$slug': typeof ColunasSlugRoute
  '/indices/$slug': typeof IndicesSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/colunas/$id': typeof AuthenticatedAdminColunasIdRoute
  '/_authenticated/admin/colunas/new': typeof AuthenticatedAdminColunasNewRoute
  '/_authenticated/admin/indices/$id': typeof AuthenticatedAdminIndicesIdRoute
  '/_authenticated/admin/indices/new': typeof AuthenticatedAdminIndicesNewRoute
  '/_authenticated/admin/colunas/': typeof AuthenticatedAdminColunasIndexRoute
  '/_authenticated/admin/indices/': typeof AuthenticatedAdminIndicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colunas'
    | '/indices'
    | '/admin'
    | '/admin/login'
    | '/colunas/$slug'
    | '/indices/$slug'
    | '/admin/'
    | '/admin/colunas/$id'
    | '/admin/colunas/new'
    | '/admin/indices/$id'
    | '/admin/indices/new'
    | '/admin/colunas/'
    | '/admin/indices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/colunas'
    | '/indices'
    | '/admin/login'
    | '/colunas/$slug'
    | '/indices/$slug'
    | '/admin'
    | '/admin/colunas/$id'
    | '/admin/colunas/new'
    | '/admin/indices/$id'
    | '/admin/indices/new'
    | '/admin/colunas'
    | '/admin/indices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/colunas'
    | '/indices'
    | '/_authenticated/admin'
    | '/admin/login'
    | '/colunas/$slug'
    | '/indices/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/colunas/$id'
    | '/_authenticated/admin/colunas/new'
    | '/_authenticated/admin/indices/$id'
    | '/_authenticated/admin/indices/new'
    | '/_authenticated/admin/colunas/'
    | '/_authenticated/admin/indices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ColunasRoute: typeof ColunasRouteWithChildren
  IndicesRoute: typeof IndicesRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/indices': {
      id: '/indices'
      path: '/indices'
      fullPath: '/indices'
      preLoaderRoute: typeof IndicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colunas': {
      id: '/colunas'
      path: '/colunas'
      fullPath: '/colunas'
      preLoaderRoute: typeof ColunasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices/$slug': {
      id: '/indices/$slug'
      path: '/$slug'
      fullPath: '/indices/$slug'
      preLoaderRoute: typeof IndicesSlugRouteImport
      parentRoute: typeof IndicesRoute
    }
    '/colunas/$slug': {
      id: '/colunas/$slug'
      path: '/$slug'
      fullPath: '/colunas/$slug'
      preLoaderRoute: typeof ColunasSlugRouteImport
      parentRoute: typeof ColunasRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/indices/': {
      id: '/_authenticated/admin/indices/'
      path: '/indices'
      fullPath: '/admin/indices/'
      preLoaderRoute: typeof AuthenticatedAdminIndicesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/colunas/': {
      id: '/_authenticated/admin/colunas/'
      path: '/colunas'
      fullPath: '/admin/colunas/'
      preLoaderRoute: typeof AuthenticatedAdminColunasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/indices/new': {
      id: '/_authenticated/admin/indices/new'
      path: '/indices/new'
      fullPath: '/admin/indices/new'
      preLoaderRoute: typeof AuthenticatedAdminIndicesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/indices/$id': {
      id: '/_authenticated/admin/indices/$id'
      path: '/indices/$id'
      fullPath: '/admin/indices/$id'
      preLoaderRoute: typeof AuthenticatedAdminIndicesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/colunas/new': {
      id: '/_authenticated/admin/colunas/new'
      path: '/colunas/new'
      fullPath: '/admin/colunas/new'
      preLoaderRoute: typeof AuthenticatedAdminColunasNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/colunas/$id': {
      id: '/_authenticated/admin/colunas/$id'
      path: '/colunas/$id'
      fullPath: '/admin/colunas/$id'
      preLoaderRoute: typeof AuthenticatedAdminColunasIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminColunasIdRoute: typeof AuthenticatedAdminColunasIdRoute
  AuthenticatedAdminColunasNewRoute: typeof AuthenticatedAdminColunasNewRoute
  AuthenticatedAdminIndicesIdRoute: typeof AuthenticatedAdminIndicesIdRoute
  AuthenticatedAdminIndicesNewRoute: typeof AuthenticatedAdminIndicesNewRoute
  AuthenticatedAdminColunasIndexRoute: typeof AuthenticatedAdminColunasIndexRoute
  AuthenticatedAdminIndicesIndexRoute: typeof AuthenticatedAdminIndicesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminColunasIdRoute: AuthenticatedAdminColunasIdRoute,
  AuthenticatedAdminColunasNewRoute: AuthenticatedAdminColunasNewRoute,
  AuthenticatedAdminIndicesIdRoute: AuthenticatedAdminIndicesIdRoute,
  AuthenticatedAdminIndicesNewRoute: AuthenticatedAdminIndicesNewRoute,
  AuthenticatedAdminColunasIndexRoute: AuthenticatedAdminColunasIndexRoute,
  AuthenticatedAdminIndicesIndexRoute: AuthenticatedAdminIndicesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ColunasRouteChildren {
  ColunasSlugRoute: typeof ColunasSlugRoute
}

const ColunasRouteChildren: ColunasRouteChildren = {
  ColunasSlugRoute: ColunasSlugRoute,
}

const ColunasRouteWithChildren =
  ColunasRoute._addFileChildren(ColunasRouteChildren)

interface IndicesRouteChildren {
  IndicesSlugRoute: typeof IndicesSlugRoute
}

const IndicesRouteChildren: IndicesRouteChildren = {
  IndicesSlugRoute: IndicesSlugRoute,
}

const IndicesRouteWithChildren =
  IndicesRoute._addFileChildren(IndicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ColunasRoute: ColunasRouteWithChildren,
  IndicesRoute: IndicesRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
